### ISSUE TITLE
Example AlayaFilePut.sh

### ISSUE THREAD

**Issue by gerbenvoshol** [ColumPaget/Alaya#4]
Hi,

First of all, thanks for writing Alaya. I was playing around with it yesterday and wanted to process a PUT request, but it says "/usr/local/sbin/AlayaFilePut.sh: not found". Can I find this file somewhere?

Thanks,
Gerben

**Comment by ColumPaget** [comment]
Hi Gerben,

Thanks for reporting this.

I think this is due to a line in the default config file, line 127:

Event=Method:PUT:/usr/local/sbin/AlayaFilePut.sh

This line says "If someone tries to do a put, run this file". The idea is that the user can supply their own script that triggers when someone tries to use http PUT. You can just comment out this line and the message should go away. I think I'll comment it out in the example config though, because it's definitely something that's going to cause confusion.

However, if the file doesn't exist it shouldn't effect the actual processing of the PUT request. Are you seeing this message in the logfiles, or is it actually being sent as an error to the browser/client when you try to PUT?

Colum

**Comment by gerbenvoshol** [comment]
Hi Colum,

Thanks. You are correct, the PUT request is correctly being processed. I commented out the line and it works.

Gerben
